/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDiseaseRouteImport } from './routes/api/disease'
import { Route as ApiVoiceRouteImport } from './routes/api/voice'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiseaseRoute = ApiDiseaseRouteImport.update({
  id: '/api/disease',
  path: '/api/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceRoute = ApiVoiceRouteImport.update({
  id: '/api/voice',
  path: '/api/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/disease': typeof ApiDiseaseRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/disease': typeof ApiDiseaseRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/disease': typeof ApiDiseaseRoute
  '/api/voice': typeof ApiVoiceRoute
  '/api/weather': typeof ApiWeatherRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/disease'
    | '/api/voice'
    | '/api/weather'
    | '/api/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/disease'
    | '/api/voice'
    | '/api/weather'
    | '/api/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/disease'
    | '/api/voice'
    | '/api/weather'
    | '/api/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDiseaseRoute: typeof ApiDiseaseRoute
  ApiVoiceRoute: typeof ApiVoiceRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/disease': {
      id: '/api/disease'
      path: '/api/disease'
      fullPath: '/api/disease'
      preLoaderRoute: typeof ApiDiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice': {
      id: '/api/voice'
      path: '/api/voice'
      fullPath: '/api/voice'
      preLoaderRoute: typeof ApiVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDiseaseRoute: ApiDiseaseRoute,
  ApiVoiceRoute: ApiVoiceRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
